### ISSUE TITLE
给tileContent 重新赋值

### ISSUE THREAD

**Issue by yywwone** [Hzy0913/mpvue-calendar#47]
我再methods 里面请求数据，然后赋值给tileContent，页面上怎么就是不显示呢

**Comment by Hzy0913** [comment]
哪个版本呢？ 贴一下代码

**Comment by zhangxiaoru** [comment]
我的也是这样，重新赋值，不显示，
![image](https://user-images.githubusercontent.com/15326045/60174297-55217e80-9843-11e9-8db7-688369b49719.png)
用注释的那种方式可以显示出来，下边的就不行

**Comment by yywwone** [comment]
你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮件 ------------------
发件人: "tian"<notifications@github.com>
发送时间: 2019年6月26日(星期三) 晚上6:51
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)



我的也是这样，重新赋值，不显示，
 
 用注释的那种方式可以显示出来，下边的就不行
 
&mdash;

**Comment by zhangxiaoru** [comment]
返回的格式一样啊。。


------------------ 原始邮件 ------------------
发件人: "yuxiaowei"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 晚上6:55
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "张晓茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)



你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮件 ------------------ 
 发件人: "tian"<notifications@github.com> 
 发送时间: 2019年6月26日(星期三) 晚上6:51 
 收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>; 
 抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47) 
 
 
 
 我的也是这样，重新赋值，不显示， 
   
  用注释的那种方式可以显示出来，下边的就不行 
   
 &mdash;

**Comment by yywwone** [comment]
你粘一下后台给你的代码，日期格式要一样------------------ 原始邮件 ------------------
发件人: "tian"<notifications@github.com>
发送时间: 2019年6月26日(星期三) 晚上7:20
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)


返回的格式一样啊。。 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "yuxiaowei"<notifications@github.com>; 
 发送时间: 2019年6月26日(星期三) 晚上6:55 
 收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>; 
 抄送: "张&#x6653;茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47) 
 
 
 
 你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "tian"<notifications@github.com>  
  发送时间: 2019年6月26日(星期三) 晚上6:51  
  收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;  
  抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)  
   
   
   
  我的也是这样，重新赋值，不显示，  
     
   用注释的那种方式可以显示出来，下边的就不行  
     
  &mdash;  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by zhangxiaoru** [comment]
啊啊，我知道了。。。看了半天。。后台返回的日期不是字符串，我一直看的我的格式，非常感谢


------------------ 原始邮件 ------------------
发件人: "yuxiaowei"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 晚上7:22
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "张晓茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)



你粘一下后台给你的代码，日期格式要一样------------------ 原始邮件 ------------------ 
 发件人: "tian"<notifications@github.com> 
 发送时间: 2019年6月26日(星期三) 晚上7:20 
 收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>; 
 抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47) 
 
 
 返回的格式一样啊。。  
   
   
  ------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "yuxiaowei"<notifications@github.com>;  
  发送时间: 2019年6月26日(星期三) 晚上6:55  
  收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;  
  抄送: "张&#x6653;茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;  
  主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)  
   
   
   
  你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮&#x4EF6; ------------------   
   发&#x4EF6;人: "tian"<notifications@github.com>   
   发送时间: 2019年6月26日(星期三) 晚上6:51   
   收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;   
   抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;   
   主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)   
     
     
     
   我的也是这样，重新赋值，不显示，   
       
    用注释的那种方式可以显示出来，下边的就不行   
       
   &mdash;   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 &mdash;

**Comment by zhangxiaoru** [comment]
看错了，是后台的月份有0。。。


------------------ 原始邮件 ------------------
发件人: "yuxiaowei"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 晚上7:22
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "张晓茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)



你粘一下后台给你的代码，日期格式要一样------------------ 原始邮件 ------------------ 
 发件人: "tian"<notifications@github.com> 
 发送时间: 2019年6月26日(星期三) 晚上7:20 
 收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>; 
 抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47) 
 
 
 返回的格式一样啊。。  
   
   
  ------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "yuxiaowei"<notifications@github.com>;  
  发送时间: 2019年6月26日(星期三) 晚上6:55  
  收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;  
  抄送: "张&#x6653;茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;  
  主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)  
   
   
   
  你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮&#x4EF6; ------------------   
   发&#x4EF6;人: "tian"<notifications@github.com>   
   发送时间: 2019年6月26日(星期三) 晚上6:51   
   收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;   
   抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;   
   主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)   
     
     
     
   我的也是这样，重新赋值，不显示，   
       
    用注释的那种方式可以显示出来，下边的就不行   
       
   &mdash;   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 &mdash;

**Comment by yywwone** [comment]
对，就是这样------------------ 原始邮件 ------------------
发件人: "tian"<notifications@github.com>
发送时间: 2019年6月26日(星期三) 晚上7:31
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)


看错了，是后台的月份有0。。。 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "yuxiaowei"<notifications@github.com>; 
 发送时间: 2019年6月26日(星期三) 晚上7:22 
 收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>; 
 抄送: "张&#x6653;茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47) 
 
 
 
 你粘一下后台给你的代码，日期格式要一样------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "tian"<notifications@github.com>  
  发送时间: 2019年6月26日(星期三) 晚上7:20  
  收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;  
  抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)  
   
   
  返回的格式一样啊。。   
     
     
   ------------------ 原始邮&#x4EF6; ------------------   
   发&#x4EF6;人: "yuxiaowei"<notifications@github.com>;   
   发送时间: 2019年6月26日(星期三) 晚上6:55   
   收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;   
   抄送: "张&#x6653;茹"<616622723@qq.com>;"Comment"<comment@noreply.github.com>;   
   主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)   
     
     
     
   你的返回值有问题，数据类型要和它保持一致，我已经改好了------------------ 原始邮&#x4EF6; ------------------    
    发&#x4EF6;人: "tian"<notifications@github.com>    
    发送时间: 2019年6月26日(星期三) 晚上6:51    
    收&#x4EF6;人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;    
    抄送: "yuxiaowei"<1607305456@qq.com>;"Author"<author@noreply.github.com>;    
    主题: Re: [Hzy0913/mpvue-calendar] 给tileContent 重新赋值 (#47)    
       
       
       
    我的也是这样，重新赋值，不显示，    
         
     用注释的那种方式可以显示出来，下边的就不行    
         
    &mdash;    
    You are receiving this because you authored the thread.    
    Reply to this email directly, view it on GitHub, or mute the thread.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  &mdash;  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;
